---
site_name: Jupiter
site_description: "Documentation for Jupiter, the life planning tool"
site_author: "Horia Coman"
copyright: "(c) 2020 Horia Coman"
repo_url: https://github.com/horia141/jupiter
repo_name: GitHub

docs_dir: docs

theme:
    name: mkdocs
    highlightjs: true
    hljs_style: obsidian

nav:
    - Tutorial: 'tutorial.md'
    - Concepts: 'concepts.md'
    - Installation: 'install.md'
    - 'How Tos':
          - Workspaces:
                - 'Initialize A Workspace': 'how-tos/workspaces/init-a-workspace.md'
    - Releases:
          - 'Version 0.3.0': 'releases/version-0.3.0.md'
          - 'Version 0.2.0': 'releases/version-0.2.0.md'
          - 'Version 0.1.6': 'releases/version-0.1.6.md'
          - Older:
                - 'Version 0.1.5': 'releases/version-0.1.5.md'
                - 'Version 0.1.4': 'releases/version-0.1.4.md'
                - 'Version 0.1.3': 'releases/version-0.1.3.md'
                - 'Version 0.1.2': 'releases/version-0.1.2.md'
                - 'Version 0.1.1': 'releases/version-0.1.1.md'
                - 'Version 0.1.0': 'releases/version-0.1.0.md'
                - 'Version 0.0.5': 'releases/version-0.0.5.md'
                - 'Version 0.0.4': 'releases/version-0.0.4.md'
                - 'Version 0.0.3': 'releases/version-0.0.3.md'
                - 'Version 0.0.2': 'releases/version-0.0.2.md'
                - 'Version 0.0.1': 'releases/version-0.0.1.md'
