---
site_name: Jupiter
site_description: "Documentation for Jupiter, the life planning tool"
site_author: "Horia Coman"
copyright: "(c) 2020 Horia Coman"
repo_url: https://github.com/horia141/jupiter
repo_name: GitHub

docs_dir: docs

theme:
    name: mkdocs
    highlightjs: true
    hljs_style: obsidian

nav:
    - Home: 'index.md'
    - Installation: 'install.md'
    - Tutorial: 'tutorial.md'
    - Concepts:
          - 'Overview': 'concepts/overview.md'
          - 'The Jupiter CLI': 'concepts/jupiter-cli.md'
          - 'Local Storage': 'concepts/local-storage.md'
          - 'Workspace': 'concepts/workspaces.md'
          - 'Vacations': 'concepts/vacations.md'
          - 'Projects': 'concepts/projects.md'
          - 'Inbox Tasks': 'concepts/inbox-tasks.md'
          - 'Recurring Tasks': 'concepts/recurring-tasks.md'
          - 'Big Plans': 'concepts/big-plans.md'
          - 'Smart Lists': 'concepts/smart-lists.md'
          - 'Metrics': 'concepts/metrics.md'
          - 'Personal Relationship Manager': 'concepts/persons.md'
          - 'Reporting': 'concepts/reporting.md'
          - 'Sync Notion And Local': 'concepts/notion-local-sync.md'
          - 'Tasks Generation': 'concepts/tasks-generation.md'
          - 'Garbage Collection': 'concepts/garbage-collection.md'
    - 'How Tos':
          - 'Garbage Collection': 'how-tos/do-garbage-collection.md'
          - 'Update An Expired Token': 'how-tos/update-an-expired-token.md'
          - 'Fix Data Inconsistencies': 'how-tos/fix-data-inconsistencies.md'
          - 'Recreate A Missing Notion Entity': 'how-tos/recreate-a-missing-notion-entity.md'
          - 'Sync From Local To Notion': 'how-tos/sync-from-local-to-notion.md'
    - Roadmap: 'roadmap.md'
    - Releases:
          - 'Version 0.9.0': 'releases/version-0.9.0.md'
          - 'Version 0.8.0': 'releases/version-0.8.0.md'
          - 'Version 0.7.0': 'releases/version-0.7.0.md'
          - Older:
                - 'Version 0.6.1': 'releases/version-0.6.1.md'
                - 'Version 0.6.0': 'releases/version-0.6.0.md'
                - 'Version 0.5.1': 'releases/version-0.5.1.md'
                - 'Version 0.5.0': 'releases/version-0.5.0.md'
                - 'Version 0.4.2': 'releases/version-0.4.2.md'
                - 'Version 0.3.0': 'releases/version-0.3.0.md'
                - 'Version 0.2.0': 'releases/version-0.2.0.md'
                - 'Version 0.1.6': 'releases/version-0.1.6.md'
                - 'Version 0.1.5': 'releases/version-0.1.5.md'
                - 'Version 0.1.4': 'releases/version-0.1.4.md'
                - 'Version 0.1.3': 'releases/version-0.1.3.md'
                - 'Version 0.1.2': 'releases/version-0.1.2.md'
                - 'Version 0.1.1': 'releases/version-0.1.1.md'
                - 'Version 0.1.0': 'releases/version-0.1.0.md'
                - 'Version 0.0.5': 'releases/version-0.0.5.md'
                - 'Version 0.0.4': 'releases/version-0.0.4.md'
                - 'Version 0.0.3': 'releases/version-0.0.3.md'
                - 'Version 0.0.2': 'releases/version-0.0.2.md'
                - 'Version 0.0.1': 'releases/version-0.0.1.md'
