---
name: Release

"on":
  push:
    tags:
      - v*

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Prepare for CI
        run: ./scripts/setup-for-ci.sh
      - name: Check scripts
        run: ./scripts/check.sh
  publish_to_docker:
    name: Publish To Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: ./scripts/docker-build.sh
      - name: Publish the docker image
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | ./scripts/docker-push.sh
