name: Release

on:
  push:
    branches:
     - master
    tags:
     - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - name: Build the docker image
       run: ./scripts/docker-build.sh
     - name: Publish the docker image
       run: echo ${{ secrets.DOCKERHUB_TOKEN }} | ./scripts/docker-push.sh
