---
name: Release

"on":
  push:
    tags:
      - v*

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Set Poetry config
        run: |
          poetry config settings.virtualenvs.in-project false
          poetry config settings.virtualenvs.path ~/.virtualenvs
      - name: Prepare for CI
        run: ./scripts/setup-for-ci.sh
      - name: Check scripts
        run: ./scripts/check.sh
  publish_to_docker:
    name: Publish To Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: ./scripts/docker-build.sh
      - name: Publish the docker image
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | ./scripts/docker-push.sh
